name: auto-release

# Disabled until repo is public
# on:
#   push:
#     tags:
#       - 'v*'

on:
  workflow_dispatch: # manual only for now

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    needs: [tests]
    uses: brickhouse-tech/.github/.github/workflows/auto-release.yml@main
