name: publish

# Disabled until repo is public and ready for npm
# on:
#   push:
#     tags:
#       - "v*"

on:
  workflow_dispatch: # manual only for now

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  publish-npm:
    needs: [tests]
    uses: brickhouse-tech/.github/.github/workflows/publish.yml@main
    permissions:
      contents: read
      id-token: write
    secrets: inherit
